{{- if .Values.operaNode.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "seleniumGrid.operaNode.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: &opera_node_labels
    app: selenium-opera-node
    app.kubernetes.io/name: selenium-opera-node
    {{- include "seleniumGrid.commonLabels" . | nindent 4 }}
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.operaNode.replicas }}
  selector:
    matchLabels:
      app: selenium-opera-node
  template:
    metadata:
      labels: *opera_node_labels
      annotations:
        checksum/event-bus-configmap: {{ include (print $.Template.BasePath "/event-bus-configmap.yaml") . | sha256sum }}
        {{- with .Values.operaNode.annotations }}
          {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: selenium-opera-node
          image: {{ printf "%s:%s" .Values.operaNode.imageName .Values.operaNode.imageTag }}
          imagePullPolicy: {{ .Values.operaNode.imagePullPolicy }}
        {{- with .Values.operaNode.extraEnvironmentVariables }}
          env: {{- tpl (toYaml .) $ | nindent 12 }}
        {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Values.busConfigMap.name }}
        {{- if gt (len .Values.operaNode.ports) 0 }}
          ports:
          {{- range .Values.operaNode.ports }}
            - containerPort: {{ . }}
              protocol: TCP
          {{- end }}
        {{- end }}
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
        {{- with .Values.operaNode.resources }}
          resources: {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
{{- end }}
