global:
  seleniumGrid:
    # Image tag for all selenium components
    imageTag: 4.0.0-rc-1-prerelease-20210804
    # Image tag for browser's nodes
    nodesImageTag: 4.0.0-rc-1-prerelease-20210804

# Deploy Router, Distributor, EventBus, SessionMap and Nodes separately
isolateComponents: false

# ConfigMap that contains SE_EVENT_BUS_HOST, SE_EVENT_BUS_PUBLISH_PORT and SE_EVENT_BUS_SUBSCRIBE_PORT variables
busConfigMap:
  # Name of the configmap
  name: selenium-event-bus-config
  # Custom annotations for configmap
  annotations: {}

# Configuration for isolated components (applied only if `isolateComponents: true`)
components:

  # Configuration for router component
  router:
    # Router image name
    imageName: selenium/router
    # Router image tag (this overwrites global.seleniumGrid.imageTag parameter)
    # imageTag: 4.0.0-rc-1-prerelease-20210804

    # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
    imagePullPolicy: IfNotPresent
    # Custom annotations for router pod
    annotations: {}
    # Router port
    port: 4444
    # Liveness probe settings
    livenessProbe:
      enabled: true
      path: /status
      initialDelaySeconds: 10
      failureThreshold: 10
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
    # Readiness probe settings
    readinessProbe:
      enabled: true
      path: /status
      initialDelaySeconds: 12
      failureThreshold: 10
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
    # Resources for router container
    resources: {}
    # Kubernetes service type (see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
    serviceType: NodePort
    # Custom annotations for router service
    serviceAnnotations: {}
    # Tolerations for router container
    tolerations: {}
    # Node selector for router container
    nodeSelector: {}

  # Configuration for distributor component
  distributor:
    # Distributor image name
    imageName: selenium/distributor
    # Distributor image tag (this overwrites global.seleniumGrid.imageTag parameter)
    # imageTag: 4.0.0-rc-1-prerelease-20210804

    # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
    imagePullPolicy: IfNotPresent
    # Custom annotations for Distributor pod
    annotations: {}
    # Distributor port
    port: 5553
    # Resources for Distributor container
    resources: {}
    # Kubernetes service type (see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
    serviceType: ClusterIP
    # Custom annotations for Distributor service
    serviceAnnotations: {}
    # Tolerations for Distributor container
    tolerations: {}
    # Node selector for Distributor container
    nodeSelector: {}

  # Configuration for Event Bus component
  eventBus:
    # Event Bus image name
    imageName: selenium/event-bus
    # Event Bus image tag (this overwrites global.seleniumGrid.imageTag parameter)
    # imageTag: 4.0.0-rc-1-prerelease-20210804

    # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
    imagePullPolicy: IfNotPresent
    # Custom annotations for Event Bus pod
    annotations: {}
    # Event Bus port
    port: 5557
    # Port where events are published
    publishPort: 4442
    # Port where to subscribe for events
    subscribePort: 4443
    # Resources for event-bus container
    resources: {}
    # Kubernetes service type (see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
    serviceType: ClusterIP
    # Custom annotations for Event Bus service
    serviceAnnotations: {}
    # Tolerations for Event Bus container
    tolerations: {}
    # Node selector for Event Bus container
    nodeSelector: {}

  # Configuration for Session Map component
  sessionMap:
    # Session Map image name
    imageName: selenium/sessions
    # Session Map image tag (this overwrites global.seleniumGrid.imageTag parameter)
    # imageTag: 4.0.0-rc-1-prerelease-20210804

    # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
    imagePullPolicy: IfNotPresent
    # Custom annotations for Session Map pod
    annotations: {}
    port: 5556
    # Resources for Session Map container
    resources: {}
    # Kubernetes service type (see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
    serviceType: ClusterIP
    # Custom annotations for Session Map service
    serviceAnnotations: {}
    # Tolerations for Session Map container
    tolerations: {}
    # Node selector for Session Map container
    nodeSelector: {}

  # Configuration for Session Queuer component
  sessionQueuer:
    # Session Queuer image name
    imageName: selenium/session-queuer
    # Session Queuer image tag (this overwrites global.seleniumGrid.imageTag parameter)
    # imageTag: 4.0.0-rc-1-prerelease-20210804

    # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
    imagePullPolicy: IfNotPresent
    # Custom annotations for Session Queuer pod
    annotations: {}
    port: 5559
    # Resources for Session Queuer container
    resources: {}
    # Kubernetes service type (see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
    serviceType: ClusterIP
    # Custom annotations for Session Queuer service
    serviceAnnotations: {}
    # Tolerations for Session Queuer container
    tolerations: {}
    # Node selector for Session Queuer container
    nodeSelector: {}

  # Custom environment variables for all components
  extraEnvironmentVariables:
    # - name: JAVA_OPTS
    #   value: "-Xmx512m"
    # - name:
    #   valueFrom:
    #     secretKeyRef:
    #       name: secret-name
    #       key: secret-key

# Configuration for selenium hub deployment (applied only if `isolateComponents: false`)
hub:
  # Selenium Hub image name
  imageName: selenium/hub
  # Selenium Hub image tag (this overwrites global.seleniumGrid.imageTag parameter)
  imageTag: 4.0.0-rc-1-prerelease-20210804
  # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  imagePullPolicy: IfNotPresent
  # Custom annotations for Selenium Hub pod
  annotations: {}
  # Port where events are published
  publishPort: 4442
  # Port where to subscribe for events
  subscribePort: 4443
  # Selenium Hub port
  port: 4444
  # Liveness probe settings
  livenessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  # Readiness probe settings
  readinessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 12
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  # Custom environment variables for selenium-hub
  extraEnvironmentVariables:
    # - name: JAVA_OPTS
    #   value: "-Xmx512m"
    # - name: SECRET_VARIABLE
    #   valueFrom:
    #     secretKeyRef:
    #       name: secret-name
    #       key: secret-key
  # Resources for selenium-hub container
  resources: {}
  # Kubernetes service type (see https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
  serviceType: NodePort
  # Custom annotations for Selenium Hub service
  serviceAnnotations: {}
  # Tolerations for selenium-hub container
  tolerations: {}
  # Node selector for selenium-hub container
  nodeSelector: {}

# Configuration for chrome nodes
chromeNode:
  # Enable chrome nodes
  enabled: true
  # Number of chrome nodes
  replicas: 1
  # Image of chrome nodes
  imageName: selenium/node-chrome
  # Image of chrome nodes (this overwrites global.seleniumGrid.nodesImageTag)
  # imageTag: 4.0.0-rc-1-prerelease-20210804
  # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  imagePullPolicy: IfNotPresent
  # Port list to enable on container
  ports:
    - 5553
  # Selenium port (spec.ports[0].targetPort in kubernetes service)
  seleniumPort: 5900
  # Selenium port exposed in service (spec.ports[0].port in kubernetes service)
  seleniumServicePort: 6900
  # Annotations for chrome-node pods
  annotations: {}
  # Resources for chrome-node container
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  # Tolerations for chrome-node container
  tolerations: {}
  # Node selector for chrome-node container
  nodeSelector: {}
  # Custom environment variables for chrome nodes
  extraEnvironmentVariables:
    # - name: JAVA_OPTS
    #   value: "-Xmx512m"
    # - name:
    #   valueFrom:
    #     secretKeyRef:
    #       name: secret-name
    #       key: secret-key
  # Service configuration
  service:
    # Create a service for node
    enabled: true
    # Service type
    type: ClusterIP
    # Custom annotations for service
    annotations: {}
  # Size limit for DSH volume mounted in container (if not set, default is "1Gi")
  dshmVolumeSizeLimit: 1Gi

# Configuration for firefox nodes
firefoxNode:
  # Enable firefox nodes
  enabled: true
  # Number of firefox nodes
  replicas: 1
  # Image of firefox nodes
  imageName: selenium/node-firefox
  # Image of firefox nodes (this overwrites global.seleniumGrid.nodesImageTag)
  # imageTag: 4.0.0-rc-1-prerelease-20210804
  # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  imagePullPolicy: IfNotPresent
  # Port list to enable on container
  ports:
    - 5553
  # Selenium port (spec.ports[0].targetPort in kubernetes service)
  seleniumPort: 5900
  # Selenium port exposed in service (spec.ports[0].port in kubernetes service)
  seleniumServicePort: 6900
  # Annotations for firefox-node pods
  annotations: {}
  # Tolerations for firefox-node container
  tolerations: {}
  # Node selector for firefox-node container
  nodeSelector: {}
  # Resources for firefox-node container
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  # Custom environment variables for firefox nodes
  extraEnvironmentVariables:
    # - name: JAVA_OPTS
    #   value: "-Xmx512m"
    # - name:
    #   valueFrom:
    #     secretKeyRef:
    #       name: secret-name
    #       key: secret-key
  # Service configuration
  service:
    # Create a service for node
    enabled: true
    # Service type
    type: ClusterIP
    # Custom annotations for service
    annotations: {}
  # Size limit for DSH volume mounted in container (if not set, default is "1Gi")
  dshmVolumeSizeLimit: 1Gi

# Configuration for opera nodes
operaNode:
  # Enable opera nodes
  enabled: true
  # Number of opera nodes
  replicas: 1
  # Image of opera nodes
  imageName: selenium/node-opera
  # Image of opera nodes (this overwrites global.seleniumGrid.nodesImageTag)
  # imageTag: 4.0.0-rc-1-prerelease-20210804
  # Image pull policy (see https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  imagePullPolicy: IfNotPresent
  ports:
    - 5553
  # Selenium port (spec.ports[0].targetPort in kubernetes service)
  seleniumPort: 5900
  # Selenium port exposed in service (spec.ports[0].port in kubernetes service)
  seleniumServicePort: 6900
  # Annotations for opera-node pods
  annotations: {}
  # Tolerations for opera-node container
  tolerations: {}
  # Node selector for opera-node container
  nodeSelector: {}
  # Resources for opera-node container
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  # Custom environment variables for firefox nodes
  extraEnvironmentVariables:
    # - name: JAVA_OPTS
    #   value: "-Xmx512m"
    # - name:
    #   valueFrom:
    #     secretKeyRef:
    #       name: secret-name
    #       key: secret-key
  # Service configuration
  service:
    # Create a service for node
    enabled: true
    # Service type
    type: ClusterIP
    # Custom annotations for service
    annotations:
      hello: world
  # Size limit for DSH volume mounted in container (if not set, default is "1Gi")
  dshmVolumeSizeLimit: 1Gi

# Custom labels for k8s resources
customLabels: {}
